# Generated by Django 3.1.4 on 2021-01-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
