# Generated by Django 3.1.4 on 2021-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='198601', max_length=6, null=True, verbose_name='인증번호'),
        ),
    ]
