# Generated by Django 3.1.4 on 2021-01-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210118_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='327981', max_length=6, null=True, verbose_name='인증번호'),
        ),
    ]
